// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskList.DAL.DataBase.Context;

#nullable disable

namespace TaskList.DAL.DataBase.Migrations
{
    [DbContext(typeof(TaskListContext))]
    [Migration("20230323010816_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskList.DAL.Interface.Models.CurrentTask", b =>
                {
                    b.Property<Guid>("CurrentTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentTaskListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentTaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CurrentTaskId");

                    b.HasIndex("CurrentTaskListId");

                    b.ToTable("CurrentTasks");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.CurrentTaskList", b =>
                {
                    b.Property<Guid>("CurrentTaskListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentTaskListName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserCurrentTaskListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrentTaskListId");

                    b.HasIndex("UserCurrentTaskListId");

                    b.ToTable("CurrentTaskLists");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.UserCurrentTaskList", b =>
                {
                    b.Property<Guid>("UserCurrentTaskListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserCurrentTaskListId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCurrentTaskLists");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.CurrentTask", b =>
                {
                    b.HasOne("TaskList.DAL.Interface.Models.CurrentTaskList", "CurrentTaskList")
                        .WithMany("CurrentTasks")
                        .HasForeignKey("CurrentTaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTaskList");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.CurrentTaskList", b =>
                {
                    b.HasOne("TaskList.DAL.Interface.Models.UserCurrentTaskList", "UserCurrentTaskList")
                        .WithMany("CurrentTaskLists")
                        .HasForeignKey("UserCurrentTaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCurrentTaskList");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.UserCurrentTaskList", b =>
                {
                    b.HasOne("TaskList.DAL.Interface.Models.User", "User")
                        .WithMany("UserCurrentTaskList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.CurrentTaskList", b =>
                {
                    b.Navigation("CurrentTasks");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.User", b =>
                {
                    b.Navigation("UserCurrentTaskList");
                });

            modelBuilder.Entity("TaskList.DAL.Interface.Models.UserCurrentTaskList", b =>
                {
                    b.Navigation("CurrentTaskLists");
                });
#pragma warning restore 612, 618
        }
    }
}
